CREATE TABLE IF NOT EXISTS Ocs (
                                   CNPJ            VARCHAR(14)   NOT NULL,
    Nome            VARCHAR(150)  NOT NULL,
    CONSTRAINT pk_ocs PRIMARY KEY (CNPJ)
    );

CREATE TABLE IF NOT EXISTS Usuario (
                                       ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                       Login           VARCHAR(60)   NOT NULL,
    Senha           VARCHAR(255)  NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (ID),
    CONSTRAINT uq_usuario_login UNIQUE (Login)
    );

CREATE TABLE IF NOT EXISTS Procedimento (
                                            ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                            Nome            VARCHAR(150)  NOT NULL,
    CONSTRAINT pk_procedimento PRIMARY KEY (ID)
    );



CREATE TABLE IF NOT EXISTS Beneficiario (
                                            PrecCP          VARCHAR(20)   NOT NULL,
    Dependente      BOOLEAN       NOT NULL DEFAULT FALSE,
    Grupo           VARCHAR(50),
    Data_Nasc       DATE,
    Nome            VARCHAR(150)  NOT NULL,
    UG              VARCHAR(100),
    Cotista         BOOLEAN       NOT NULL DEFAULT FALSE,
    Usuario_ID      INT,
    CONSTRAINT pk_beneficiario PRIMARY KEY (PrecCP),
    CONSTRAINT uq_beneficiario_usuario UNIQUE (Usuario_ID),
    CONSTRAINT fk_beneficiario_usuario FOREIGN KEY (Usuario_ID)
    REFERENCES Usuario (ID)
    ON UPDATE CASCADE ON DELETE SET NULL
    );

CREATE TABLE IF NOT EXISTS FunOcs (
                                      ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                      Cargo           VARCHAR(80),
    Ocs_ID          VARCHAR(14)   NOT NULL,
    Usuario_ID      INT           NOT NULL,
    CONSTRAINT pk_funocs PRIMARY KEY (ID),
    CONSTRAINT uq_funocs_usuario UNIQUE (Usuario_ID),
    CONSTRAINT fk_funocs_ocs FOREIGN KEY (Ocs_ID)
    REFERENCES Ocs (CNPJ)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_funocs_usuario FOREIGN KEY (Usuario_ID)
    REFERENCES Usuario (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );



CREATE TABLE IF NOT EXISTS Medico (
                                      ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                      CRM             VARCHAR(20)   NOT NULL,
    Benef_ID        VARCHAR(20)   NOT NULL,
    CONSTRAINT pk_medico PRIMARY KEY (ID),
    CONSTRAINT uq_medico_crm UNIQUE (CRM),
    CONSTRAINT fk_medico_benef FOREIGN KEY (Benef_ID)
    REFERENCES Beneficiario (PrecCP)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS Auditor (
                                       ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                       Benef_ID        VARCHAR(20)   NOT NULL,
    CONSTRAINT pk_auditor PRIMARY KEY (ID),
    CONSTRAINT fk_auditor_benef FOREIGN KEY (Benef_ID)
    REFERENCES Beneficiario (PrecCP)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS Analista (
                                        ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                        Benef_ID        VARCHAR(20)   NOT NULL,
    CONSTRAINT pk_analista PRIMARY KEY (ID),
    CONSTRAINT fk_analista_benef FOREIGN KEY (Benef_ID)
    REFERENCES Beneficiario (PrecCP)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS Chefe_Fusex (
                                           ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                           Benef_ID        VARCHAR(20)   NOT NULL,
    CONSTRAINT pk_chefe_fusex PRIMARY KEY (ID),
    CONSTRAINT fk_chefe_benef FOREIGN KEY (Benef_ID)
    REFERENCES Beneficiario (PrecCP)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );



CREATE TABLE IF NOT EXISTS Espelho (
                                       ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                       Data_Inicio     DATE          NOT NULL,
                                       Data_Fim        DATE          NOT NULL,
                                       Ocs_ID          VARCHAR(14)   NOT NULL,
    FunOcs_ID       INT           NOT NULL,
    Auditor_ID      INT,
    CONSTRAINT pk_espelho PRIMARY KEY (ID),
    CONSTRAINT fk_espelho_ocs FOREIGN KEY (Ocs_ID)
    REFERENCES Ocs (CNPJ)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_espelho_funocs FOREIGN KEY (FunOcs_ID)
    REFERENCES FunOcs (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_espelho_auditor FOREIGN KEY (Auditor_ID)
    REFERENCES Auditor (ID)
    ON UPDATE CASCADE ON DELETE SET NULL
    );



CREATE TABLE IF NOT EXISTS Contrato (
                                        ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                        Proc_ID         INT           NOT NULL,
                                        Ocs_ID          VARCHAR(14)   NOT NULL,
    Valor           NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_contrato PRIMARY KEY (ID),
    CONSTRAINT fk_contrato_proc FOREIGN KEY (Proc_ID)
    REFERENCES Procedimento (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_contrato_ocs FOREIGN KEY (Ocs_ID)
    REFERENCES Ocs (CNPJ)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE IF NOT EXISTS Guia (
                                    ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                    Benf_ID         VARCHAR(20)   NOT NULL,
    Med_ID          INT           NOT NULL,
    Emissor_ID      INT           NOT NULL,
    Chefe_ID        INT           NOT NULL,
    PDF             VARCHAR(255),
    Status          VARCHAR(30)   NOT NULL,
    Data            DATE          NOT NULL,
    CONSTRAINT pk_guia PRIMARY KEY (ID),
    CONSTRAINT fk_guia_benef FOREIGN KEY (Benf_ID)
    REFERENCES Beneficiario (PrecCP)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_guia_medico FOREIGN KEY (Med_ID)
    REFERENCES Medico (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_guia_emissor FOREIGN KEY (Emissor_ID)
    REFERENCES Analista (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_guia_chefe FOREIGN KEY (Chefe_ID)
    REFERENCES Chefe_Fusex (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );


CREATE TABLE IF NOT EXISTS Guia_Proc (
                                         ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                         Cont_ID         INT           NOT NULL,
                                         Guia_ID         INT           NOT NULL,
                                         QR              VARCHAR(255),
    Status          VARCHAR(30)   NOT NULL,
    CONSTRAINT pk_guia_proc PRIMARY KEY (ID),
    CONSTRAINT fk_gp_contrato FOREIGN KEY (Cont_ID)
    REFERENCES Contrato (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_gp_guia FOREIGN KEY (Guia_ID)
    REFERENCES Guia (ID)
    ON UPDATE CASCADE ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS Fatura (
                                      ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                                      Guia_Proc_ID    INT           NOT NULL,
                                      Esp_Fat         INT           NOT NULL,
                                      CONSTRAINT pk_fatura PRIMARY KEY (ID),
    CONSTRAINT fk_fatura_gp FOREIGN KEY (Guia_Proc_ID)
    REFERENCES Guia_Proc (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_fatura_espelho FOREIGN KEY (Esp_Fat)
    REFERENCES Espelho (ID)
    ON UPDATE CASCADE ON DELETE RESTRICT
    );