ALTER TABLE Espelho
    ALTER COLUMN Ocs_ID DROP NOT NULL,
ALTER COLUMN FunOcs_ID DROP NOT NULL;

ALTER TABLE Espelho
    ADD COLUMN Atendimento_ID INT NOT NULL,
    ADD CONSTRAINT uq_espelho_atendimento UNIQUE (Atendimento_ID),
    ADD CONSTRAINT fk_espelho_atendimento FOREIGN KEY (Atendimento_ID)
        REFERENCES Guia_Proc (ID)
        ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE Espelho_Item (
                              ID              INT           GENERATED BY DEFAULT AS IDENTITY,
                              Espelho_ID      INT           NOT NULL,
                              Atendimento_ID  INT           NOT NULL,
                              Beneficiario_ID VARCHAR(20)   NOT NULL,
                              Descricao       VARCHAR(150)  NOT NULL,
                              Valor           NUMERIC(10,2) NOT NULL,
                              CONSTRAINT pk_espelho_item PRIMARY KEY (ID),
                              CONSTRAINT fk_item_espelho FOREIGN KEY (Espelho_ID)
                                  REFERENCES Espelho (ID)
                                  ON UPDATE CASCADE ON DELETE CASCADE,
                              CONSTRAINT fk_item_atendimento FOREIGN KEY (Atendimento_ID)
                                  REFERENCES Guia_Proc (ID)
                                  ON UPDATE CASCADE ON DELETE RESTRICT,
                              CONSTRAINT fk_item_beneficiario FOREIGN KEY (Beneficiario_ID)
                                  REFERENCES Beneficiario (PrecCP)
                                  ON UPDATE CASCADE ON DELETE RESTRICT
);