CREATE TABLE Item_Fatura (
                             ID                 INT           GENERATED BY DEFAULT AS IDENTITY,
                             Fatura_ID          INT           NOT NULL,
                             Espelho_Item_ID    INT           NOT NULL,
                             Valor_Apresentado  NUMERIC(10,2) NOT NULL,
                             Valor_Contratado   NUMERIC(10,2) NOT NULL,
                             Divergencia_Valor  NUMERIC(10,2) NOT NULL,
                             CONSTRAINT pk_item_fatura PRIMARY KEY (ID),
                             CONSTRAINT fk_item_fatura_fatura FOREIGN KEY (Fatura_ID)
                                 REFERENCES Fatura (ID)
                                 ON UPDATE CASCADE ON DELETE CASCADE,
                             CONSTRAINT fk_item_fatura_espelho_item FOREIGN KEY (Espelho_Item_ID)
                                 REFERENCES Espelho_Item (ID)
                                 ON UPDATE CASCADE ON DELETE RESTRICT
);